import 'semantic-ui-css/semantic.min.css';
import { Inter } from "next/font/google";
import { Container } from 'semantic-ui-react';
import EventManagementContextProvider from "./context/EventContractContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <EventManagementContextProvider>
          {/* <Container>
            <Header />
          </Container> */}
          <Container>
            {children}
          </Container>
        </EventManagementContextProvider>
      </body>
    </html>
  );
}
